---
version: '3.1'

volumes:
  transactions-data:
  rewards-data:

services:
  rewards:
    build:
      context: ../sunpro_rewards
    volumes:
      - ../sunpro_rewards:/app
    env_file:
      - .env
    ports:
      - 4000:4000
      - 4443:4443
      - 4042:4042
    command:
      - mix
      - phx.server
    depends_on:
      - transactionsdb
      - rewardsdb

  transactions:
    build:
      context: ../sunpro_transactions
    volumes:
      - ../sunpro_transactions:/app
    env_file:
      - .env
    command:
      - mix
      - run
      - --no-halt
    depends_on:
      - transactionsdb
      # - mssql is optional

  transactionsdb:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_DB: sunpro_transactions_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - transactions-data:/var/lib/postgresql/data
    ports:
      - 4032:5432

  rewardsdb:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_DB: sunpro_rewards_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - rewards-data:/var/lib/postgresql/data
    ports:
      - 4033:5432

  mssql:
    build:
      context: ../sunpro_transactions/docker/mssql/
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: Sunroc7Rewards7Development
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - ../sunpro_transactions/tmp:/usr/src/tmp
      - ../sunpro_transactions/docker/mssql/Rewards_Data_View.tsv:/app/docker/mssql/Rewards_Data_View.tsv
      - ../sunpro_transactions/docker/mssql/Customer_Dimension.tsv:/app/docker/mssql/Customer_Dimension.tsv
